apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: order-service
    spec:
      containers:
        - args:
            - npm
            - run
            - start
            - --workspace=backend/services/order
          env:
            - name: DATABASE_URL
              value: mongodb://mongodb:27017/orderdb?replicaSet=rs0
            - name: INVENTORY_SVC_URL
              value: http://inventory-service:3003
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger:4318
            - name: PAYMENT_SVC_URL
              value: http://payment-service:3005
            - name: PORT
              value: "3004"
            - name: RABBITMQ_URL
              value: amqp://app:app@rabbitmq:5672
            - name: USER_SVC_URL
              value: http://user-service:3001
          image: order-service
          imagePullPolicy: Never
          name: order-service
      restartPolicy: Always
